###############################################################################
# Author: <YOUR NAME>
# Name: webapp-deploy-template
#
# This reusable workflow defines the steps required to deploy an Azure Web App
# It is intended to be used by all Azure Web Apps workflows.
###############################################################################

name: webapp-deploy-template

on: 
  workflow_call:
    inputs:
      ENVIRONMENT_PREFIX:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      AZURE_WEBAPP_NAME:
        required: true
        type: string
      AZURE_WEBAPP_SKU:
        type: string
        default: 'F1'
      AZURE_WEBAPP_LINUXFXVERSION:
        type: string
        default: 'DOTNETCORE|6.0'
      STARTUP_COMMAND:
        type: string
        default: ''
      LOCATION:
        type: string
        default: 'canadacentral'
      RESOURCE_GROUP:
        required: true
        type: string
      DEPLOYMENT_MODE:
        type: string
        default: 'Incremental'
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_SUBSCRIPTIONID:
        required: true
      APP_SETTINGS:
        required: false
      CONNECTION_STRINGS:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT}}

    env:
      envPrefix: ${{ inputs.ENVIRONMENT_PREFIX }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4.1.7
      id: download
      with:
        name: artifacts

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep Template (Web App Infra)
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTIONID }}
        resourceGroupName: '${{ inputs.ENVIRONMENT_PREFIX }}-${{inputs.RESOURCE_GROUP}}'
        deploymentMode: '${{ inputs.DEPLOYMENT_MODE }}'
        template: 'azuredeploy.bicep'
        parameters: > 
          envPrefix=${{ inputs.ENVIRONMENT_PREFIX }} 
          webAppName=${{ inputs.AZURE_WEBAPP_NAME }}
          sku=${{ inputs.AZURE_WEBAPP_SKU }}
          linuxFxVersion=${{ inputs.AZURE_WEBAPP_LINUXFXVERSION }}
          location=${{ inputs.LOCATION }}
        failOnStdErr: false

    - name: 'Deploy Web App'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ inputs.ENVIRONMENT_PREFIX }}-${{ inputs.AZURE_WEBAPP_NAME }}
        package: ${{steps.download.outputs.download-path}}
        startup-command: ${{ inputs.STARTUP_COMMAND }}

    - name: Configure App Settings
      uses: azure/appservice-settings@v1
      with:
        app-name: ${{ inputs.ENVIRONMENT_PREFIX }}-${{ inputs.AZURE_WEBAPP_NAME }}
        app-settings-json: ${{ secrets.APP_SETTINGS }} 
        connection-strings-json: ${{ secrets.CONNECTION_STRINGS }}

    - name: Log out of Azure
      run: az logout